apiVersion: apps/v1
kind: Deployment
metadata:
  name: sbt_k8s-deployment
  labels:
    app: sbt_k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sbt_k8s
  template:
    metadata:
      labels:
        app: sbt_k8s
    spec:
      containers:
        - image: zalozhnyy/sbt_k8s:latest
          name: sbt_k8s
          imagePullPolicy: "IfNotPresent"
          # define a liveness probe that checks every 5 seconds, starting after 5 seconds
          livenessProbe:
            httpGet:
              path: /live
              port: 8086
            initialDelaySeconds: 5
            periodSeconds: 5
          # define a readiness probe that checks every 5 seconds
          readinessProbe:
            httpGet:
              path: /ready
              port: 8086
            periodSeconds: 5
          ports:
            - containerPort: 3000
              protocol: TCP
            - containerPort: 8000
              protocol: TCP
